modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Superflat%20World%20No%20Slimes"
logoFile="icon.png"

[[mods]]
modId="superflatworldnoslimes"
version="3.0"
displayName="Superflat World No Slimes"
displayURL="https://curseforge.com/minecraft/mc-mods/superflat-world-no-slimes"
authors="Rick South"
description='''Removes those pesky slimes when you're trying to be creative in a superflat world.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.superflatworldnoslimes]]
    modId="collective"
    mandatory=true
    versionRange="[6.7,)"
    ordering="NONE"
    side="BOTH"